version: "2"
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
    - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
    - "1888:1888"   # pprof extension
    - "13133:13133" # health_check extension
    - "55679:55679" # zpages extension
    - "4317:4317"   # OTLP gRPC receiver
    - "4318:4318"   # OTLP http receiver
    depends_on:
    - jaeger-all-in-one
    - zipkin-all-in-one
