receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
  #otlphttp:
  #  endpoint: https://example.com:4318/v1/traces
  #file:
  #  path: ./otel-collector-export.json

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, jaeger] #, file]
