name: otel-api-context
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache-2.0
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @otel-api-context@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -fwarn-tabs
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  dependencies:
  - base >=4.11.1.0 && <5
  - exceptions
  - monad-control
  - monad-logger
  - mtl
  - otel-api-context-core
  - resourcet
  - text
  - transformers
  - transformers-base
  - unliftio-core
  source-dirs: library
  when:
  - condition: false
    other-modules: Paths_otel_api_context

tests:
  otel-api-context-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - base
    - hspec
    - otel-api-context
    - otel-api-context-core
    - text
    - transformers
    - unliftio-core
    when:
    - condition: false
      other-modules: Paths_otel_api_context
