name: hotel-api
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @hotel@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - base
  - hotel-api-trace
  source-dirs: library
