name: otel-sdk-trace
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache-2.0
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @otel-sdk-trace@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -fwarn-tabs
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  dependencies:
  - aeson
  - base >=4.11.1.0 && <5
  - clock
  - dlist
  - monad-logger-aeson
  - mtl
  - mwc-random
  - otel-api-common
  - otel-api-context-core
  - otel-api-trace
  - otel-api-trace-core
  - safe-exceptions
  - stm
  - stm-chans
  - text
  - unliftio-core
  - vector
  source-dirs: library
  when:
  - condition: false
    other-modules: Paths_otel_sdk_trace

tests:
  otel-sdk-trace-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - HUnit
    - base
    - containers
    - hspec
    - monad-logger-aeson
    - otel-api-common
    - otel-api-trace
    - otel-api-trace-core
    - otel-sdk-trace
    - safe-exceptions
    - stm
    - stm-chans
    - text
    - transformers
    - unliftio-core
    when:
    - condition: false
      other-modules: Paths_otel_sdk_trace
