name: otel-api-common
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache-2.0
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @otel-api-common@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -fwarn-tabs
- -Wincomplete-uni-patterns
- -Wredundant-constraints

library:
  dependencies:
  - aeson
  - base >=4.11.1.0 && <5
  - containers
  - dlist
  - hashable
  - scientific
  - text
  - unordered-containers
  - vector
  source-dirs: library
  when:
  - condition: false
    other-modules: Paths_otel_api_common

tests:
  otel-api-common-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - aeson
    - base
    - hspec
    - otel-api-common
    - scientific
    - text
    when:
    - condition: false
      other-modules: Paths_otel_api_common
