name: otel-api-common
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache-2.0
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @otel-api-common@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
- -Wall
- -fwarn-tabs
- -Wincomplete-uni-patterns
- -Wredundant-constraints

flags:
  aeson-pre-2-2:
    description: Build with aeson <2.2
    manual: false
    default: true

library:
  source-dirs: library
  dependencies:
  - async
  - base >=4.11.1.0 && <5
  - bytestring
  - containers
  - dlist
  - hashable
  - monad-logger-aeson
  - safe-exceptions
  - scientific
  - text
  - transformers
  - unliftio-core
  - unordered-containers
  - vector
  when:
  - condition: flag(aeson-pre-2-2)
    then:
      dependencies:
      - aeson <2.2.0.0
    else:
      dependencies:
      - aeson >=2.2.0.0
      - attoparsec-aeson >=2.2.0.0
  - condition: false
    other-modules: Paths_otel_api_common

tests:
  otel-api-common-test-suite:
    source-dirs: test-suite
    main: Driver.hs
    build-tools:
    - hspec-discover
    dependencies:
    - base
    - hspec
    - monad-logger-aeson
    - otel-api-common
    - scientific
    - stm
    - text
    when:
    - condition: flag(aeson-pre-2-2)
      then:
        dependencies:
        - aeson <2.2.0.0
      else:
        dependencies:
        - aeson >=2.2.0.0
        - attoparsec-aeson >=2.2.0.0
    - condition: false
      other-modules: Paths_otel_api_common
