name: otel-api-trace-core
version: '0.0.0'
github: "jship/opentelemetry-haskell"
license: Apache-2.0
license-file: LICENSE
copyright: 2022 (c) Jason Shipman
author: "Jason Shipman"
maintainer: "Jason Shipman"
synopsis: STUB
description: |
  @otel-api-trace-core@ STUB
category: System

extra-source-files:
- package.yaml
- README.md
- LICENSE
- CHANGELOG.md

default-extensions:
- NoImplicitPrelude

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  dependencies:
  - aeson
  - base >=4.11.1.0 && <5
  - bytestring
  - dlist
  - exceptions
  - monad-control
  - monad-logger
  - otel-api-context-core
  - otel-api-common
  - resourcet
  - text
  - transformers
  - unliftio-core
  - unordered-containers
  - vector
  source-dirs: library
  when:
  - condition: false
    other-modules: Paths_otel_api_trace_core
