name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly # ghc-9.2.4

    steps:
    - uses: actions/checkout@v3
    - id: stack
      #uses: freckle/stack-action@v4
      uses: jship/stack-action@stack-work-dir-by-yaml-dir
      with:
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest' && matrix.resolver == 'nightly'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.stack.outputs.local-doc-root }}
