name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - nightly # ghc-9.6.2
        - lts-21  # ghc-9.4.5
        - lts-20  # ghc-9.2.8

    steps:
    - uses: actions/checkout@v3
    - id: stack
      uses: freckle/stack-action@v4
      with:
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock
    - uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest' && matrix.resolver == 'nightly'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.stack.outputs.local-doc-root }}
